### ISSUE TITLE
Rails 4 Custom Session Class

### ISSUE THREAD

**Issue by jpb** [rails/activerecord-session_store#9]
In Rails 4, setting `ActiveRecord::SessionStore.session_class = Session` in `config/session_store.rb` returns `NoMethodError: undefined method 'session_class=' for ActiveRecord::SessionStore:Module`. The same assignment seems to work fine in Rails 3.2.
